### ISSUE TITLE
Git is unable to checkout submodule "Git"

### ISSUE THREAD

**Issue by thomasrehm** [thm-projects/arsnova-vagrant#26]
Hey,
i tried to update my local repo of arsnova-vagrant and all of its submodules via `git submodules update --init --recursive`. Most submodules work fine and are pulled, but **Git** as a submodule cannot be found. Here is the proof: 

	Thomas:arsnova-vagrant Thomas$ git submodule update --init --recursive
	Submodule path 'puppet/modules/apache': checked out '3ad5b244c947b173007df5b27da48376284eb438'
	Submodule path 'puppet/modules/apt': checked out '98d16464c32d17e449cc12dd2406654afe81f397'
	Submodule path 'puppet/modules/concat': checked out 'f70881fbfd01c404616e9e4139d98dad78d5a918'
	fatal: reference is not a tree: 828f1fa21caba18a862ab67b57e32ccebe4e4185
	Submodule path 'puppet/modules/java': checked out 'a089f326ca3a975724cb492e1606fc1261e47921'
	Submodule path 'puppet/modules/jenkins': checked out '781df5e90bbdcb5e1233abe922bec7be490c8a93'
	Submodule path 'puppet/modules/motd': checked out '1a3544f3b2fd8cfc4089cf4abadf74b953c6b025'
	Submodule path 'puppet/modules/sonarqube': checked out '828948a7dc7ceef08fad3946af629068c096c350'
	Submodule path 'puppet/modules/stdlib': checked out 'f9f6e92dffa8364cfbbd92a6a65f4be4ef176d2c'
	Submodule path 'puppet/modules/wget': checked out '16a164e529194c2a9f96987f04ff42fcccfdca88'
	Unable to checkout '828f1fa21caba18a862ab67b57e32ccebe4e4185' in submodule path 'puppet/modules/git'

My local repo is up-to-date to the latest commit in branch **synced-folder-performance**.
Because I haven't had the time yet, I haven't tried it to boot the vagrant machine up.
(git version 2.4.3, OS X 10.10.3)

**Comment by commana** [comment]
The Repository of the Git submodule has changed. Try `git submodule sync` first before updating the modules.

**Comment by thomasrehm** [comment]
Thank you! It worked. I cannot imagine why this occured, I just did a complete fresh clone (with --recursive) before.
