### ISSUE TITLE
maven build fails

### ISSUE THREAD

**Issue by dhx** [thm-projects/arsnova-vagrant#27]
Since commit 79cb66a428ffc1d17f5ec24d2a9b57b46b41e692 arsnova-backend depends on pl.project13.maven/git-commit-id-plugin which in turn requires Maven version [3.1.1,).

Unfortunately on the vagrant image there is only 

```
vagrant@arsnova-dev:~$ mvn -v
Apache Maven 3.0.4
```

**Comment by commana** [comment]
Thanks for reporting. The whole base box is due for an update. Unfortunately, we're probably not going to be able to fix this any time soon. Maybe you could help us out on this? That would be greatly appreciated!

**Comment by dhx** [comment]
https://github.com/thm-projects/arsnova-vagrant/pull/28

btw. the thm maven repo seems to have problems currently (502 Bad Gateway)
