### ISSUE TITLE
arsnova-info.mni.thm.de down

### ISSUE THREAD

**Issue by dhx** [thm-projects/arsnova-vagrant#30]
As the virtual box image is an external hosted one, we currently get the following error message when trying to use this project:

> $ vagrant up dev
> Bringing machine 'dev' up with 'virtualbox' provider...
> ==> dev: Box 'commana/arsnova-debian-wheezy-puppet3-amd64' could not be found. Attempting to find and install...
>     dev: Box Provider: virtualbox
>     dev: Box Version: >= 0
> ==> dev: Loading metadata for box 'commana/arsnova-debian-wheezy-puppet3-amd64'
>     dev: URL: https://vagrantcloud.com/commana/arsnova-debian-wheezy-puppet3-amd64
> ==> dev: Adding box 'commana/arsnova-debian-wheezy-puppet3-amd64' (v0.1.0) for provider: virtualbox
>     dev: Downloading: https://vagrantcloud.com/commana/boxes/arsnova-debian-wheezy-puppet3-amd64/versions/0.1.0/providers/virtualbox.box
> An error occurred while downloading the remote file. The error
> message, if any, is reproduced below. Please fix this error and try
> again.
> 
> Failed to connect to arsnova-info.mni.thm.de port 80: Verbindungsaufbau abgelehnt
>

**Comment by dgerhardt** [comment]
I have updated the image location but please note that arsnova-vagrant is not actively maintained at the moment.
